openapi: "3.0.0"
info:
  version: 1.0.0
  title: Planner API Documentation
servers:
  - url: http://127.0.0.1:8080
paths:
  /worker:
    post:
      summary: Service for saving worker
      operationId: saveWorker
      description: Save Worker
      tags:
        - Worker
      requestBody:
        $ref: '#/components/requestBodies/WorkerRequestBody'
      responses:
        200:
          description: OK
        400:
          $ref: '#/components/responses/ErrorResponseBody'
  /workers:
    get:
      summary: Service for getting all workers
      operationId: getAllWorkers
      description: Get All Workers
      tags:
        - Worker
      responses:
        200:
          description: OK
          $ref: '#/components/responses/WorkerResponseBody'
        400:
          $ref: '#/components/responses/ErrorResponseBody'
  /slots:
    get:
      summary: Service for get all slots information
      operationId: getSlots
      description: Get All Slots
      tags:
        - Slots
      responses:
        200:
          description: OK
          $ref: '#/components/responses/SlotsResponseBody'
        400:
          $ref: '#/components/responses/ErrorResponseBody'
  /assign:
    post:
      summary: Service for assigning slot to worker
      operationId: assignSlot
      description: Assign Slot
      tags:
        - Roster
      requestBody:
        $ref: '#/components/requestBodies/RosterRequestBody'
      responses:
        200:
          description: OK
        400:
          $ref: '#/components/responses/ErrorResponseBody'

components:
  requestBodies:
    WorkerRequestBody:
      description: Save Worker Request Body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WorkerRequest'
    RosterRequestBody:
      description: Assign Slot to Worker
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AssignSlotRequest'
  responses:
    ErrorResponseBody:
      description: Response that contains error information
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    WorkerResponseBody:
      description: Return all workers
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/WorkerResponse'
    SlotsResponseBody:
      description: Return all slots
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SlotResponse'
  schemas:
    #Requests
    WorkerRequest:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    AssignSlotRequest:
      type: object
      properties:
        slot_id:
          type: number
        worker_id:
          type: number
        date:
          type: string
      required:
        - slot_id
        - worker_id
        - date
    # RESPONSES
    ErrorResponse:
      properties:
        code:
          type: string
        title:
          type: string
        message:
          type: string
    WorkerResponse:
      properties:
        id:
          type: number
        name:
          type: string
    SlotResponse:
      properties:
        id:
          type: number
        name:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        duration:
          type: string
